[package]
name = "stm32flash"
version = "0.1.0"
edition = "2024"

[dependencies]
stm32-bootloader-client = { git = "https://github.com/xboxoneresearch/stm32-bootloader-client-rs.git", branch = "task/update_deps" }
i2c = { path = "../i2c" }
indicatif = "0.18.0"
